on:
  push:
    tags:
    - '*.*.*'

name: Release

jobs:
  create_release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
  upload_artifacts:
    name: Artifacts
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      
      - name: Generate the artifacts
        uses: skx/github-action-build@master
      
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'dnschecker*'