on:
  push:
    tags:
    - '*.*.*'

name: Release

jobs:
  create_release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate the artifacts
        uses: skx/github-action-build@master
        
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dnschecker
            dnschecker-x86
            dnschecker-arm32
            dnschecker-arm64
            dnschecker.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}